export const UNITS = [
  { id: "crane_hallb_5t",    label: "Crane 5T",           type: "crane",            hall: "Hall B", icon: "🏗️" },
  { id: "crane_hallb_10t",   label: "Crane 10T",          type: "crane",            hall: "Hall B", icon: "🏗️" },
  { id: "crane_halld_32t",   label: "Crane 32T",          type: "crane",            hall: "Hall D", icon: "🏗️" },
  { id: "forklift_electric", label: "Forklift Elektrik",  type: "forklift_electric", hall: "–",     icon: "🔋" },
  { id: "forklift_gas",      label: "Forklift Gas",       type: "forklift_gas",      hall: "–",     icon: "⛽" },
]

export const CHECKLIST = {
  crane: [
    { id: "cr01", cat: "Struktur Mekanik",  item: "Kondisi boom/girder tidak retak atau bengkok" },
    { id: "cr02", cat: "Struktur Mekanik",  item: "Hook & safety latch (pengunci hook) berfungsi baik" },
    { id: "cr03", cat: "Struktur Mekanik",  item: "Wire rope: tidak ada kawat putus, kinking, atau karat berlebih" },
    { id: "cr04", cat: "Struktur Mekanik",  item: "Sheave/pulley berputar bebas, tidak ada bunyi abnormal" },
    { id: "cr05", cat: "Struktur Mekanik",  item: "End stop/buffer rel dalam kondisi baik" },
    { id: "cr06", cat: "Sistem Pelumasan",  item: "Level oli gear box dalam batas normal" },
    { id: "cr07", cat: "Sistem Pelumasan",  item: "Tidak ada kebocoran oli di area trolley/hoist" },
    { id: "cr08", cat: "Rem & Drive",       item: "Rem hoist berfungsi — uji angkat beban kecil" },
    { id: "cr09", cat: "Rem & Drive",       item: "Rem travel (long/cross) berfungsi normal" },
    { id: "cr10", cat: "Rem & Drive",       item: "Tidak ada bunyi abnormal saat hoist/travel dijalankan" },
    { id: "cr11", cat: "Elektrikal",        item: "Limit switch hoist atas & bawah berfungsi" },
    { id: "cr12", cat: "Elektrikal",        item: "Limit switch travel (end stop) berfungsi" },
    { id: "cr13", cat: "Elektrikal",        item: "Pendant control/remote: semua tombol responsif" },
    { id: "cr14", cat: "Elektrikal",        item: "Horn/buzzer alarm berfungsi" },
    { id: "cr15", cat: "Elektrikal",        item: "Lampu indikator panel menyala normal" },
    { id: "cr16", cat: "Keselamatan",       item: "Load indicator/SWL terpasang dan terbaca jelas" },
    { id: "cr17", cat: "Keselamatan",       item: "Kondisi rel crane tidak ada kerusakan/sambungan lepas" },
    { id: "cr18", cat: "Keselamatan",       item: "Area bawah crane bebas dari orang/material tidak perlu" },
    { id: "cr19", cat: "Keselamatan",       item: "APAR di area crane tersedia & tidak kadaluarsa" },
    { id: "cr20", cat: "Keselamatan",       item: "Operator memiliki SIO aktif dan telah briefing K3 pagi ini" },
  ],
  forklift_electric: [
    { id: "fe01", cat: "Baterai & Charging", item: "Level charge baterai ≥ 20% (tidak boleh operasi di bawah ini)" },
    { id: "fe02", cat: "Baterai & Charging", item: "Konektor baterai tidak longgar, tidak ada korosi terminal" },
    { id: "fe03", cat: "Baterai & Charging", item: "Tidak ada kebocoran elektrolit / bau menyengat dari baterai" },
    { id: "fe04", cat: "Baterai & Charging", item: "Charger sudah dilepas sebelum operasi" },
    { id: "fe05", cat: "Mast & Garpu",       item: "Garpu (fork) tidak retak, bengkok, atau aus berlebihan" },
    { id: "fe06", cat: "Mast & Garpu",       item: "Mast bergerak naik-turun mulus, tidak ada sentakan" },
    { id: "fe07", cat: "Mast & Garpu",       item: "Rantai angkat (lift chain) tidak kendur/retak" },
    { id: "fe08", cat: "Mast & Garpu",       item: "Tilt cylinder tidak bocor, tilt maju-mundur normal" },
    { id: "fe09", cat: "Hidrolik",           item: "Level oli hidrolik dalam batas normal" },
    { id: "fe10", cat: "Hidrolik",           item: "Tidak ada kebocoran oli di bawah unit" },
    { id: "fe11", cat: "Ban & Roda",         item: "Kondisi ban tidak retak/sobek" },
    { id: "fe12", cat: "Ban & Roda",         item: "Baut roda terpasang kencang" },
    { id: "fe13", cat: "Kemudi & Rem",       item: "Steering responsif, tidak ada free play berlebih" },
    { id: "fe14", cat: "Kemudi & Rem",       item: "Rem servis pakem, tidak ada bunyi gesekan aneh" },
    { id: "fe15", cat: "Kemudi & Rem",       item: "Rem parkir berfungsi, unit tidak bergerak saat diaktifkan" },
    { id: "fe16", cat: "Kelistrikan",        item: "Horn berfungsi" },
    { id: "fe17", cat: "Kelistrikan",        item: "Lampu depan, belakang & strobo berfungsi" },
    { id: "fe18", cat: "Kelistrikan",        item: "Indikator baterai/jam operasi terbaca normal di dashboard" },
    { id: "fe19", cat: "Keselamatan",        item: "Sabuk pengaman operator tersedia dan berfungsi" },
    { id: "fe20", cat: "Keselamatan",        item: "Overhead guard tidak rusak/bengkok" },
    { id: "fe21", cat: "Keselamatan",        item: "Backrest extension (sandaran beban) terpasang kokoh" },
    { id: "fe22", cat: "Keselamatan",        item: "Operator memiliki SIO aktif dan telah briefing K3 pagi ini" },
  ],
  forklift_gas: [
    { id: "fg01", cat: "Bahan Bakar Gas",    item: "Tekanan tabung LPG/CNG dalam batas operasi normal" },
    { id: "fg02", cat: "Bahan Bakar Gas",    item: "Regulator gas tidak bocor (uji dengan air sabun)" },
    { id: "fg03", cat: "Bahan Bakar Gas",    item: "Selang gas tidak retak, tidak ada kebocoran di sambungan" },
    { id: "fg04", cat: "Bahan Bakar Gas",    item: "Bracket/pengikat tabung gas terpasang kencang" },
    { id: "fg05", cat: "Mesin",              item: "Oli mesin pada level yang benar (dipstick)" },
    { id: "fg06", cat: "Mesin",              item: "Level air radiator/coolant dalam batas normal" },
    { id: "fg07", cat: "Mesin",              item: "Mesin hidup normal, tidak ada asap berlebihan atau bunyi knocking" },
    { id: "fg08", cat: "Mesin",              item: "Tidak ada kebocoran bahan bakar/oli di bawah unit" },
    { id: "fg09", cat: "Mast & Garpu",       item: "Garpu (fork) tidak retak, bengkok, atau aus berlebihan" },
    { id: "fg10", cat: "Mast & Garpu",       item: "Mast bergerak naik-turun mulus" },
    { id: "fg11", cat: "Mast & Garpu",       item: "Rantai angkat (lift chain) tidak kendur/retak" },
    { id: "fg12", cat: "Mast & Garpu",       item: "Tilt cylinder tidak bocor" },
    { id: "fg13", cat: "Hidrolik",           item: "Level oli hidrolik dalam batas normal" },
    { id: "fg14", cat: "Ban & Roda",         item: "Kondisi ban tidak retak/sobek" },
    { id: "fg15", cat: "Ban & Roda",         item: "Baut roda terpasang kencang" },
    { id: "fg16", cat: "Kemudi & Rem",       item: "Steering responsif" },
    { id: "fg17", cat: "Kemudi & Rem",       item: "Rem servis pakem" },
    { id: "fg18", cat: "Kemudi & Rem",       item: "Rem parkir berfungsi" },
    { id: "fg19", cat: "Kelistrikan",        item: "Horn berfungsi" },
    { id: "fg20", cat: "Kelistrikan",        item: "Lampu depan, belakang & strobo berfungsi" },
    { id: "fg21", cat: "Keselamatan",        item: "APAR (1 kg) tersedia di unit, tidak kadaluarsa" },
    { id: "fg22", cat: "Keselamatan",        item: "Sabuk pengaman operator tersedia dan berfungsi" },
    { id: "fg23", cat: "Keselamatan",        item: "Overhead guard tidak rusak" },
    { id: "fg24", cat: "Keselamatan",        item: "Operator memiliki SIO aktif dan telah briefing K3 pagi ini" },
  ],
}
